version = 1

[schema]

[[schema.tables]]
id = 0
name = "chat_poll_votes"
primary_key = { columns = [{ table = 0, index = 0 }], index = { table = 0, index = 0 } }

[[schema.tables.columns]]
id = { table = 0, index = 0 }
name = "id"
ty = "U64"
storage_ty = { UnsignedInteger = 4 }
auto_increment = true

[[schema.tables.columns]]
id = { table = 0, index = 1 }
name = "poll_id"
ty = "U64"
storage_ty = { UnsignedInteger = 8 }

[[schema.tables.columns]]
id = { table = 0, index = 2 }
name = "voter_key"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 0, index = 3 }
name = "option_number"
ty = "U64"
storage_ty = { UnsignedInteger = 8 }

[[schema.tables.indices]]
id = { table = 0, index = 0 }
name = "index_chat_poll_votes_by_id"
on = 0
columns = [{ column = { table = 0, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 0, index = 1 }
name = "index_chat_poll_votes_by_poll_and_voter"
on = 0
columns = [{ column = { table = 0, index = 1 }, op = "Eq", scope = "Partition" }, { column = { table = 0, index = 2 }, op = "Eq", scope = "Local" }]
unique = true

[[schema.tables]]
id = 1
name = "chat_poll"
primary_key = { columns = [{ table = 1, index = 0 }], index = { table = 1, index = 0 } }

[[schema.tables.columns]]
id = { table = 1, index = 0 }
name = "id"
ty = "U64"
storage_ty = { UnsignedInteger = 8 }

[[schema.tables.columns]]
id = { table = 1, index = 1 }
name = "question"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 1, index = 2 }
name = "options_data"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 1, index = 3 }
name = "started_at_unix_ms"
ty = "U64"
storage_ty = { UnsignedInteger = 8 }

[[schema.tables.columns]]
id = { table = 1, index = 4 }
name = "stopped_at_unix_ms"
ty = "U64"
storage_ty = { UnsignedInteger = 8 }
nullable = true

[[schema.tables.columns]]
id = { table = 1, index = 5 }
name = "results_ends_at_unix_ms"
ty = "U64"
storage_ty = { UnsignedInteger = 8 }
nullable = true

[[schema.tables.indices]]
id = { table = 1, index = 0 }
name = "index_chat_poll_by_id"
on = 1
columns = [{ column = { table = 1, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables]]
id = 2
name = "chat_pomodoro"
primary_key = { columns = [{ table = 2, index = 0 }], index = { table = 2, index = 0 } }

[[schema.tables.columns]]
id = { table = 2, index = 0 }
name = "id"
ty = "U64"
storage_ty = { UnsignedInteger = 8 }

[[schema.tables.columns]]
id = { table = 2, index = 1 }
name = "message"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 2, index = 2 }
name = "started_at_unix_ms"
ty = "U64"
storage_ty = { UnsignedInteger = 8 }

[[schema.tables.columns]]
id = { table = 2, index = 3 }
name = "ends_at_unix_ms"
ty = "U64"
storage_ty = { UnsignedInteger = 8 }

[[schema.tables.indices]]
id = { table = 2, index = 0 }
name = "index_chat_pomodoro_by_id"
on = 2
columns = [{ column = { table = 2, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables]]
id = 3
name = "chat_state"
primary_key = { columns = [{ table = 3, index = 0 }], index = { table = 3, index = 0 } }

[[schema.tables.columns]]
id = { table = 3, index = 0 }
name = "id"
ty = "U64"
storage_ty = { UnsignedInteger = 8 }

[[schema.tables.columns]]
id = { table = 3, index = 1 }
name = "dropped"
ty = "U64"
storage_ty = { UnsignedInteger = 8 }

[[schema.tables.indices]]
id = { table = 3, index = 0 }
name = "index_chat_state_by_id"
on = 3
columns = [{ column = { table = 3, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables]]
id = 4
name = "chat_seen"
primary_key = { columns = [{ table = 4, index = 0 }], index = { table = 4, index = 0 } }

[[schema.tables.columns]]
id = { table = 4, index = 0 }
name = "id"
ty = "U64"
storage_ty = { UnsignedInteger = 4 }
auto_increment = true

[[schema.tables.columns]]
id = { table = 4, index = 1 }
name = "source"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 4, index = 2 }
name = "external_id"
ty = "String"
storage_ty = "Text"

[[schema.tables.indices]]
id = { table = 4, index = 0 }
name = "index_chat_seen_by_id"
on = 4
columns = [{ column = { table = 4, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 4, index = 1 }
name = "index_chat_seen_by_source_and_external_id"
on = 4
columns = [{ column = { table = 4, index = 1 }, op = "Eq", scope = "Partition" }, { column = { table = 4, index = 2 }, op = "Eq", scope = "Local" }]
unique = true

[[schema.tables]]
id = 5
name = "chat_messages"
primary_key = { columns = [{ table = 5, index = 0 }], index = { table = 5, index = 0 } }

[[schema.tables.columns]]
id = { table = 5, index = 0 }
name = "id"
ty = "U64"
storage_ty = { UnsignedInteger = 4 }
auto_increment = true

[[schema.tables.columns]]
id = { table = 5, index = 1 }
name = "source"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 5, index = 2 }
name = "external_id"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 5, index = 3 }
name = "author"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 5, index = 4 }
name = "text"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 5, index = 5 }
name = "emoji_data"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 5, index = 6 }
name = "avatar_url"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 5, index = 7 }
name = "sent_at"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 5, index = 8 }
name = "received_at_unix_ms"
ty = "U64"
storage_ty = { UnsignedInteger = 8 }

[[schema.tables.indices]]
id = { table = 5, index = 0 }
name = "index_chat_messages_by_id"
on = 5
columns = [{ column = { table = 5, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables]]
id = 6
name = "app_config"
primary_key = { columns = [{ table = 6, index = 0 }], index = { table = 6, index = 0 } }

[[schema.tables.columns]]
id = { table = 6, index = 0 }
name = "id"
ty = "I64"
storage_ty = { Integer = 8 }

[[schema.tables.columns]]
id = { table = 6, index = 1 }
name = "data"
ty = "String"
storage_ty = "Text"

[[schema.tables.indices]]
id = { table = 6, index = 0 }
name = "index_app_config_by_id"
on = 6
columns = [{ column = { table = 6, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true
